export type State = "IDLE" | "EXPLAIN_WORD" | "EXPLAIN_WORD_AGAIN" | "ASK_QUESTION" | "END";

export type Event = "START" | "USER_UNDERSTOOD" | "USER_DID_NOT_UNDERSTAND" | "USER_RESPONDS_CORRECTLY_TO_QUESTION" | "USER_RESPONDS_WRONG_TO_QUESTION" | "SUCCESSFUL_COMPLETION";